# .github/workflows/ocmin.yml

name: opencog min

on:
  push:
    branches: main
  pull_request:
    branches: main

jobs:
  build-and-test:
    name: Build and Test All Components
    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v4
      
      - name: Install dependencies
        run: |
          sudo apt-get update
          sudo apt-get install -y build-essential cmake libboost-all-dev librocksdb-dev liboctomap-dev guile-3.0-dev uuid-dev cython3 python3-nose valgrind doxygen
          
      - name: Install Cython
        run: python3 -m pip install --upgrade pip cython

      - name: build & install opencog
        run: |
          mkdir -p cogutil/build/ && cd cogutil/build && cmake .. && sudo make install && sudo ldconfig && cd ../..
          mkdir -p atomspace/build/ && cd atomspace/build && cmake .. && sudo make install && sudo ldconfig && cd ../..
          mkdir -p atomspace-storage/build/ && cd atomspace-storage/build && cmake .. && sudo make install && sudo ldconfig && cd ../..
          mkdir -p atomspace-rocks/build/ && cd atomspace-rocks/build && cmake .. && sudo make install && sudo ldconfig && cd ../..
          mkdir -p cogserver/build/ && cd cogserver/build && cmake .. && sudo make install && sudo ldconfig && cd ../..
          mkdir -p unify/build/ && cd unify/build && cmake .. && sudo make install && sudo ldconfig && cd ../..
          mkdir -p ure/build/ && cd ure/build && cmake .. && sudo make install && sudo ldconfig && cd ../..
          mkdir -p attention/build/ && cd attention/build && cmake .. && sudo make install && sudo ldconfig && cd ../..
          mkdir -p miner/build/ && cd miner/build && cmake .. && sudo make install && sudo ldconfig && cd ../..
          mkdir -p pln/build/ && cd pln/build && cmake .. && sudo make install && sudo ldconfig && cd ../..
          mkdir -p lg-atomese/build/ && cd lg-atomese/build && cmake .. && sudo make install && sudo ldconfig && cd ../..
          mkdir -p learn/build/ && cd learn/build && cmake .. && sudo make install && sudo ldconfig && cd ../..
          mkdir -p opencog/build/ && cd opencog/build && cmake .. && sudo make install && sudo ldconfig && cd ../..


